Ext.define('Ecfa.Config', {
	singleton : true,
	/* others */
	DATETIME_FORMAT : 'Y/m/d H:i:s',
	DATE_FORMAT : 'Y/m/d',
	TIME_FORMAT : 'H:i:s',

	// Test result is generated by seista in WebContent\app\data
	// The files must have .json extension. Eg: up_result_chrome.json
	test_result_files : [ 'up_result_chrome', 'op_result_chrome' ]

});
