Ext.define('MyApp.Config', {
	singleton : true,
	/* others */
	DATETIME_FORMAT : 'Y/m/d H:i:s',
	DATE_FORMAT : 'Y/m/d',
	TIME_FORMAT : 'H:i:s',

	// Test result is generated by seista in WebContent\app\data	
	test_result_files : [ {
		display : 'UP in Chrome', // display is optional
		fileName : 'up_result_chrome.json'
	}, {
		display : 'OP in Chrome',
		fileName : 'op_result_chrome.json'
	} ]

});
