
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Ext.setting.panel.Table": "app/ExtSetting.js",
  "Ext.enchance.grid.column.Column": "app/ExtOverride.js",
  "Ext.enhance.panel.Panel": "app/ExtOverride.js",
  "Ext.setting.grid.view": "app/ExtSetting.js",
  "Ext.enhance.data.Store": "app/ExtOverride.js",
  "Ext.ux.GroupTreeChunker": "ext/src/ux/GroupTabPanel.js",
  "Ext.Container.forground": "app/ExtOverride.js",
  "Ext.enhance.form.BasicForm": "app/ExtOverride.js",
  "Ext": "ext/src",
  "Ecfa": "app",
  "Ext.enhance.form.action.Submit": "app/ExtOverride.js",
  "Ext.enhance.tree.Panel": "app/ExtOverride.js",
  "Ext.enhance.Container": "app/ExtOverride.js",
  "Ext.enhance.grid.Panel": "app/ExtOverride.js",
  "Ext.enhance.Component": "app/ExtOverride.js",
  "Ext.enhance.form.field.File": "app/ExtOverride.js",
  "Ext.enhance.tab.Panel": "app/ExtOverride.js",
  "Ext.setting.grid.Panel": "app/ExtSetting.js",
  "Ext.setting.MenuItem": "app/ExtSetting.js",
  "Ext.enhance.ux.RowExpander": "app/ExtOverride.js",
  "Ext.enhance.Action": "app/ExtOverride.js",
  "Ext.enhance.data.Connection": "app/ExtOverride.js",
  "Ext.enhance.ux.form.ItemSelector": "app/ExtOverride.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "Ecfa.action.Action": [],
  "Ecfa.ux.i18n.model.Property": [],
  "Ext.ux.grid.TransformGrid": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.enhance.form.BasicForm": [],
  "Ext.ux.event.Driver": [],
  "Ext.ux.ajax.XmlSimlet": [],
  "Ext.ux.DataView.DragSelector": [],
  "Ecfa.ExtFix": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Ecfa.Const": [],
  "Ext.ux.form.MultiSelect": [
    "Ext.ux.Multiselect"
  ],
  "Ext.ux.CheckColumn": [],
  "Ext.ux.PreviewPlugin": [],
  "Ecfa.event.Account": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [],
  "Ecfa.ux.i18n.reader.Property": [],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.ajax.Simlet": [],
  "Ext.enchance.grid.column.Column": [],
  "Ext.ux.SlidingPager": [],
  "Ecfa.ExtSetting": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [],
  "Ext.setting.grid.view": [],
  "Ecfa.store.queue.Job": [],
  "Ext.ux.event.Recorder": [],
  "Ecfa.event.QueueManagement": [],
  "Ecfa.controller.Queue": [],
  "Ecfa.locale.Converter": [],
  "Ecfa.view.MainToolbar": [],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.grid.filter.BooleanFilter": [],
  "Ext.enhance.data.Connection": [],
  "Ext.ux.TabScrollerMenu": [],
  "Ext.ux.IFrame": [],
  "Ecfa.event.Task": [],
  "Ecfa.controller.Main": [],
  "Ecfa.event.ModelEvent": [],
  "Ext.ux.form.SearchField": [],
  "Ecfa.view.Viewport": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.Container.forground": [],
  "Ecfa.ux.i18n.Bundle": [],
  "Ext.ux.grid.filter.DateFilter": [],
  "Ext.ux.TreePicker": [],
  "Ecfa.ExtOverride": [],
  "Ext.enhance.tree.Panel": [],
  "Ext.setting.grid.Panel": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "Ext.data.PagingMemoryProxy"
  ],
  "Ext.ux.BoxReorderer": [],
  "Ecfa.event.File": [],
  "Ext.setting.panel.Table": [],
  "Ext.ux.grid.filter.Filter": [],
  "Ecfa.view.queue.JobGrid": [],
  "Ext.ux.FieldReplicator": [],
  "Ecfa.event.Project": [],
  "Ext.ux.grid.filter.ListFilter": [],
  "Ext.enhance.tab.Panel": [],
  "Ext.setting.MenuItem": [],
  "Ext.ux.GMapPanel": [],
  "Ecfa.Session": [],
  "Ext.ux.GroupTabPanel": [],
  "Ext.ux.DataView.LabelEditor": [],
  "Ecfa.event.Problem": [],
  "Ext.ux.grid.filter.StringFilter": [],
  "Ext.ux.GroupTreeChunker": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Ext.ux.layout.Center": [],
  "Ext.ux.DataView.Animated": [],
  "Ext.enhance.form.field.File": [],
  "Ecfa.view.Main": [],
  "Ext.ux.statusbar.StatusBar": [
    "Ext.ux.StatusBar"
  ],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.RowExpander": [],
  "Ecfa.model.queue.Job": [],
  "Ext.ux.event.Player": [],
  "Ext.enhance.grid.Panel": [],
  "Ext.enhance.Container": [],
  "Ext.enhance.Component": [],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.event.Maker": [],
  "Ecfa.event.Submission": [],
  "Ext.enhance.panel.Panel": [],
  "Ecfa.event.Queue": [],
  "Ext.ux.DataView.Draggable": [],
  "Ecfa.event.User": [],
  "Ext.ux.TabCloseMenu": [],
  "Ecfa.Config": [],
  "Ext.enhance.data.Store": [],
  "Ecfa.event.Model": [],
  "Ext.ux.form.ItemSelector": [
    "Ext.ux.ItemSelector"
  ],
  "Ext.ux.ajax.JsonSimlet": [],
  "Ext.enhance.form.action.Submit": [],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [],
  "Ext.enhance.ux.RowExpander": [],
  "Ecfa.event.Graph": [],
  "Ext.enhance.Action": [],
  "Ext.enhance.ux.form.ItemSelector": []
});
Ext.ClassManager.addNameAliasMappings({
  "Ecfa.action.Action": [],
  "Ecfa.ux.i18n.model.Property": [],
  "Ext.ux.grid.TransformGrid": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.enhance.form.BasicForm": [],
  "Ext.ux.event.Driver": [],
  "Ext.ux.ajax.XmlSimlet": [
    "simlet.xml"
  ],
  "Ext.ux.DataView.DragSelector": [],
  "Ecfa.ExtFix": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Ecfa.Const": [],
  "Ext.ux.form.MultiSelect": [
    "widget.multiselect",
    "widget.multiselectfield"
  ],
  "Ext.ux.CheckColumn": [
    "widget.checkcolumn"
  ],
  "Ext.ux.PreviewPlugin": [
    "plugin.preview"
  ],
  "Ecfa.event.Account": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [
    "widget.eventrecordermanager"
  ],
  "Ecfa.ux.i18n.reader.Property": [
    "reader.property"
  ],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.ajax.Simlet": [
    "simlet.basic"
  ],
  "Ext.enchance.grid.column.Column": [],
  "Ext.ux.SlidingPager": [],
  "Ecfa.ExtSetting": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [
    "gridfilter.numeric"
  ],
  "Ext.setting.grid.view": [],
  "Ecfa.store.queue.Job": [],
  "Ext.ux.event.Recorder": [],
  "Ecfa.event.QueueManagement": [],
  "Ecfa.controller.Queue": [],
  "Ecfa.locale.Converter": [],
  "Ecfa.view.MainToolbar": [],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.grid.filter.BooleanFilter": [
    "gridfilter.boolean"
  ],
  "Ext.enhance.data.Connection": [],
  "Ext.ux.TabScrollerMenu": [
    "plugin.tabscrollermenu"
  ],
  "Ext.ux.IFrame": [
    "widget.uxiframe"
  ],
  "Ecfa.event.Task": [],
  "Ecfa.controller.Main": [],
  "Ecfa.event.ModelEvent": [],
  "Ext.ux.form.SearchField": [
    "widget.searchfield"
  ],
  "Ecfa.view.Viewport": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.Container.forground": [],
  "Ecfa.ux.i18n.Bundle": [],
  "Ext.ux.grid.filter.DateFilter": [
    "gridfilter.date"
  ],
  "Ext.ux.TreePicker": [
    "widget.treepicker"
  ],
  "Ecfa.ExtOverride": [],
  "Ext.enhance.tree.Panel": [],
  "Ext.setting.grid.Panel": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "proxy.pagingmemory"
  ],
  "Ext.ux.BoxReorderer": [],
  "Ecfa.event.File": [],
  "Ext.setting.panel.Table": [],
  "Ext.ux.grid.filter.Filter": [],
  "Ecfa.view.queue.JobGrid": [
    "widget.jobGrid"
  ],
  "Ext.ux.FieldReplicator": [],
  "Ecfa.event.Project": [],
  "Ext.ux.grid.filter.ListFilter": [
    "gridfilter.list"
  ],
  "Ext.enhance.tab.Panel": [],
  "Ext.setting.MenuItem": [],
  "Ext.ux.GMapPanel": [
    "widget.gmappanel"
  ],
  "Ecfa.Session": [],
  "Ext.ux.GroupTabPanel": [
    "widget.grouptabpanel"
  ],
  "Ext.ux.DataView.LabelEditor": [],
  "Ecfa.event.Problem": [],
  "Ext.ux.grid.filter.StringFilter": [
    "gridfilter.string"
  ],
  "Ext.ux.GroupTreeChunker": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Ext.ux.layout.Center": [
    "layout.ux.center"
  ],
  "Ext.ux.DataView.Animated": [],
  "Ext.enhance.form.field.File": [],
  "Ecfa.view.Main": [],
  "Ext.ux.statusbar.StatusBar": [
    "widget.statusbar"
  ],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.RowExpander": [
    "plugin.rowexpander"
  ],
  "Ecfa.model.queue.Job": [],
  "Ext.ux.event.Player": [],
  "Ext.enhance.grid.Panel": [],
  "Ext.enhance.Container": [],
  "Ext.enhance.Component": [],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.event.Maker": [],
  "Ecfa.event.Submission": [],
  "Ext.enhance.panel.Panel": [],
  "Ecfa.event.Queue": [],
  "Ext.ux.DataView.Draggable": [],
  "Ecfa.event.User": [],
  "Ext.ux.TabCloseMenu": [
    "plugin.tabclosemenu"
  ],
  "Ecfa.Config": [],
  "Ext.enhance.data.Store": [],
  "Ecfa.event.Model": [],
  "Ext.ux.form.ItemSelector": [
    "widget.itemselector",
    "widget.itemselectorfield"
  ],
  "Ext.ux.ajax.JsonSimlet": [
    "simlet.json"
  ],
  "Ext.enhance.form.action.Submit": [],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [
    "feature.filters"
  ],
  "Ext.enhance.ux.RowExpander": [],
  "Ecfa.event.Graph": [],
  "Ext.enhance.Action": [],
  "Ext.enhance.ux.form.ItemSelector": []
});
